create table tb_account (id bigint generated by default as identity, number varchar(255), primary key (id));
create table tb_account_wallets (account_id bigint not null, wallets_id bigint not null unique);
create table tb_merchant (id bigint generated by default as identity, mcc varchar(255), name varchar(255), primary key (id));
create table tb_transaction (amount numeric(38,2), type smallint check (type between 0 and 2), account_id bigint unique, creation_date timestamp(6), id bigint generated by default as identity, merchant_id bigint unique, wallet_id bigint unique, transaction_code varchar(255), primary key (id));
create table tb_wallet (amount numeric(38,2), account_id bigint, id bigint generated by default as identity, type varchar(255) check (type in ('FOOD','MEAL','CASH')), primary key (id));
alter table if exists tb_account_wallets add constraint FKl75sn3uukrqtcve6klfwr5d1f foreign key (wallets_id) references tb_wallet;
alter table if exists tb_account_wallets add constraint FK4d06vvci3tughhqkt87o9ueyy foreign key (account_id) references tb_account;
alter table if exists tb_transaction add constraint FKiggeh1ugt959fee13yghgkave foreign key (account_id) references tb_account;
alter table if exists tb_transaction add constraint FKhw7sbsyucvjdxca61r98uqd4n foreign key (merchant_id) references tb_merchant;
alter table if exists tb_transaction add constraint FKe40ju7fgbq7lcv7l6g544gtat foreign key (wallet_id) references tb_wallet;
alter table if exists tb_wallet add constraint FKg2kv17kq5i2o2f3bh38s5ua3u foreign key (account_id) references tb_account;

INSERT INTO public.tb_account ("number") VALUES ('123');
INSERT INTO public.tb_merchant (mcc, "name") VALUES ('5411', 'LAYANNE FOOD');
INSERT INTO public.tb_merchant (mcc, "name") VALUES ('5412', 'LAYANNE MEAL');
INSERT INTO public.tb_wallet (amount, account_id, "type") VALUES (100, 1, 'FOOD');
INSERT INTO public.tb_wallet (amount, account_id, "type") VALUES (100, 1, 'MEAL');
INSERT INTO public.tb_wallet (amount, account_id, "type") VALUES (100, 1, 'CASH');